const movies = [
  {
    id: 1,
    title: 'A lista de Schindler',
    director: 'Steven Spielberg',
    storyline: 'O alemão Oskar Schindler viu na mão de obra judia uma solução barata e viável para lucrar com negócios durante a guerra. Com sua forte influência dentro do partido nazista, foi fácil conseguir as autorizações e abrir uma fábrica. O que poderia parecer uma atitude de um homem não muito bondoso, transformou-se em um dos maiores casos de amor à vida da História, pois este alemão abdicou de toda sua fortuna para salvar a vida de mais de mil judeus em plena luta contra o extermínio alemão.',
    year: 1993,
    imagePath: 'images/a_lista_de_schindler.png',
    genre: 'Guerra/Drama',
  },
  {
    id: 2,
    title: 'Uma Linda Mulher',
    director: 'Garry Marshall',
    storyline: 'Durante uma viagem de negócios a Los Angeles, Edward, um executivo que compra e fragmenta empresas para vendê-las, encontra a prostituta Vivian. Edward a contrata para ficar com ele durante uma semana a fim de acompanhá-lo nos jantares de negócios. Os dois se aproximam e descobrem que há vários obstáculos para serem superados até que possam unir seus mundos tão diferentes.',
    year: 1990,
    imagePath: 'images/uma_linda_mulher.jpg',
    genre: 'Romance/Comédia Romântica',
  },
  {
    id: 3,
    title: 'Edward Mãos de Tesoura',
    director: 'Tim Burton',
    storyline: 'Peg Boggs é uma vendedora que acidentalmente descobre Edward, jovem que mora sozinho em um castelo no topo de uma montanha, criado por um inventor que morreu antes de dar mãos ao estranho ser, que possui apenas enormes lâminas no lugar delas. Isto o impede de poder se aproximar dos humanos, a não ser para criar revolucionários cortes de cabelos. No entanto, Edward é vítima da sua inocência e, se é amado por uns, é perseguido e usado por outros.',
    year: 1990,
    imagePath: 'images/edwards_maos_de_tesoura.jpg',
    genre: 'Fantasia/Romance',
  },
  {
    id: 4,
    title: 'Entrevista com o Vampiro',
    director: 'Neil Jordan',
    storyline: 'Um jornalista biógrafo cheio de suspeitas entrevista um jovem que afirma ser vampiro, em São Francisco, nos anos 1990. Louis de Pointe du Lac, um homem que perdeu tudo, narra suas experiências dos últimos 200 anos e reconta seu encontro com Lestat de Lioncourt, uma criatura da noite que o tornou um vampiro e o ensinou a viver de uma nova maneira.',
    year: 1994,
    imagePath: 'images/entrevista-com-o-vampiro.jpg',
    genre: 'Terror/Romance',
  },
  {
    id: 5,
    title: 'O Silêncio dos Inocentes',
    director: 'Jonathan Demme',
    storyline: 'Uma jovem e talentosa agente do FBI é aconselhada pelo Dr. Hannibal Lecter, um psiquiatra brilhante e também um psicopata violento e canibal, a fim de conseguir capturar outro assassino.',
    year: 1991,
    imagePath: 'images/o_silencio_dos_inocentes.jpg',
    genre: 'Thriller/Terror',
  },
  {
    id: 6,
    title: 'Toy Story',
    director: 'John Lasseter',
    storyline: 'O aniversário do garoto Andy está chegando e seus brinquedos ficam nervosos, temendo que ele ganhe novos brinquedos que possam substituí-los. Liderados pelo caubói Woody, o brinquedo predileto de Andy, eles recebem Buzz Lightyear, o boneco de um patrulheiro espacial, que logo passa a receber mais atenção do garoto. Com ciúmes, Woody tenta ensiná-lo uma lição, mas Buzz cai pela janela. É o início da aventura do caubói, que precisa resgatar Buzz para limpar sua barra com os outros brinquedos.',
    year: 1995,
    imagePath: 'images/toy_story.jpg',
    genre: 'Infantil/Comédia',
  },
  {
    id: 7,
    title: 'Esqueceram de Mim',
    director: 'Chris Columbus',
    storyline: 'Quando o levado Kevin McCallister, de oito anos de idade, não se comporta na noite anterior de uma viagem da família para Paris, sua mãe o faz dormir no sótão, e ele deseja que sua família não estivesse em casa. Após os McCallisters irem para o aeroporto sem Kevin, que acorda e acredita que o seu desejo de não ter família se tornou realidade, ele percebe que dois vigaristas planejam roubar a residência. Sozinho, ele precisa proteger a casa da família destes atrapalhados ladrões.',
    year: 1990,
    imagePath: 'images/esqueceram_de_mim.jpg',
    genre: 'Comédia/Infantil',
  },
  {
    id: 8,
    title: 'Matilda',
    director: 'Danny DeVitto',
    storyline: 'Matilda é uma criança brilhante que cresceu em meio a pais grosseiros e ignorantes. Ambos ignoram a filha, a ponto de esquecerem de matriculá-la na escola. Desta forma, Matilda fica sempre em casa ou na livraria, onde costuma estimular sua imaginação. Quando Matilda descobre que possui poderes mágicos, Harry resolve enviá-la à escola. O local é controlado com mão de ferro pela diretora Agatha Trunchbull, então Matilda precisa usar seu talento especial para proteger seus amigos e sua professora.',
    year: 1996,
    imagePath: 'images/matilda.jpg',
    genre: 'Infantil/Comédia',
  },
  {
    id: 9,
    title: 'Uma babá quase perfeita',
    director: 'Chris Columbus',
    storyline: 'Preocupado por ter pouco acesso aos seus filhos, o divorciado Daniel Hillard (Robin Williams) elabora um plano. Com a ajuda de seu irmão criativo Frank (Harvey Fierstein), ele se veste como uma velha mulher britânica e convence sua ex-mulher, Miranda (Sally Field), para contratá-lo como babá. As crianças adoram a Sra. Doubtfire e com sua ajuda, Daniel se torna um pai melhor. Porém quando ambos Daniel e sua persona babá vão ao mesmo restaurante, a situação os deixa em apuros.',
    year: 1993,
    imagePath: 'images/uma_baba_quase_perfeita.jpg',
    genre: 'Infantil/Comédia',
  },
  {
    id: 10,
    title: 'Os Batutinhas',
    director: 'Penelope Spheeris',
    storyline: 'A turma de pestinhas embarca em mais uma história cheia de confusões! Alfafa é julgado culpado em uma reunião do Clube dos Homens que Odeiam Mulheres, porque se apaixonou por Darla. Seus amigos fazem de tudo para acabar com o romance dos dois, mas Alfafa está disposto a continuar o namoro.',
    year: 1983,
    imagePath: 'images/os_batutinhas.jpg',
    genre: 'Infantil/Comédia',
  },
  {
    id: 11,
    title: 'Jumanji',
    director: 'Joe Johnston',
    storyline: 'Alan Parrish desapareceu quando era menino e ninguém acredita na história de seu amigo de que ele foi sugado por um jogo. Vinte e seis anos depois, duas crianças acham o jogo no sótão e, quando começam a jogar, Alan é libertado. Mas o jogo ainda não acabou e Alan precisa terminar antes de ser realmente libertado.',
    year: 1995,
    imagePath: 'images/jumanji.jpg',
    genre: 'Infantil/Fantasia',
  },
  {
    id: 12,
    title: 'Família Adams',
    director: 'Barry Sonnenfeld',
    storyline: 'Quando um homem dizendo ser Funério, o irmão desaparecido de Gomez Addams, chega à casa dos Addams, a família está feliz. No entanto, Morticia começa a suspeitar que Funério é uma fraude, já que ele não consegue se lembrar de detalhes da sua vida. Com a ajuda do advogado Tully Alford, Funério consegue fazer com que o clã Addams seja despejado de sua casa. Gomez percebe que os dois homens estão conspirando para roubar a fortuna de sua família.',
    year: 1991,
    imagePath: 'images/a_familia_adams.jpg',
    genre: 'Comédia/Fantasia',
  },
  {
    id: 13,
    title: 'O Escorpião Jade',
    director: 'Woody Allen',
    storyline: 'Na década de 1940, o investigador de seguros C.W. Briggs encara o desafio de capturar um ladrão que usa os poderes hipnóticos do misterioso Escorpião de Jade antes que o criminoso consiga dominar sua mente e o leve para o caminho do roubo.',
    year: 2001,
    imagePath: 'images/o_escorpiao_de_jade.jpg',
    genre: 'Comédia/Romance',
  },
  {
    id: 14,
    title: 'Querida, encolhi as crianças',
    director: 'Joe Johnston',
    storyline: 'O cientista Wayne Szalinski tem como resultado de uma má experiência o encolhimento acidental dos seus dois filhos adolescentes. Além deles, também encolhe sem querer dois meninos da vizinhança, e todos ficam do tamanho de insetos. Agora, os adolescentes vão ter que enfrentar diversos problemas por serem tão pequenos, enquanto o pai procura por eles, e também por uma solução.',
    year: 1989,
    imagePath: 'images/querida_encolhi_as_criancas.jpg',
    genre: 'Infantil/Comédia',
  },
  {
    id: 15,
    title: 'Guerra nas Estrelas - O império contra-ataca',
    director: 'Irvin Kershner',
    storyline: 'Yoda treina Luke Skywalker para ser um cavaleiro Jedi. Han Solo corteja a Princesa Leia enquanto Darth Vader retorna para combater as forças rebeldes que tentam salvar a galáxia.',
    year: 1980,
    imagePath: 'images/o_imperio_contra_ataca.jpg',
    genre: 'Ficção Científica/Ação',
  },
  {
    id: 16,
    title: 'Karate-Kid - A Hora da Verdade',
    director: 'John G. Avildsen',
    storyline: 'O adolescente Daniel LaRusso se envolve com a ex-namorada do valentão da escola e começa a ser atormentado por sua gangue. Para sua sorte, ele conta com os ensinamentos do senhor Miyagi, um mestre de karatê que o prepara para autodefesa e também para um importante campeonato.',
    year: 1984,
    imagePath: 'images/karate_kid.jpg',
    genre: 'Drama/Ação',
  },
  {
    id: 17,
    title: 'A História sem Fim',
    director: 'Wolfgang Petersen',
    storyline: 'O garoto Bastian encontra um livro que fala sobre uma terra chamada Fantasia, um lugar onde a escuridão destrói tudo. Fantasia aguarda pela salvação, que virá de um humano exatamente igual a ele.',
    year: 1984,
    imagePath: 'images/a_historia_sem_fim.jpg',
    genre: 'Fantasia/Infantil',
  },
  {
    id: 18,
    title: 'Os Fantasmas se Divertem',
    director: 'Tim Burton',
    storyline: 'Depois de morrerem em um acidente de carro, Bárbara e Adam Maitland se encontram presos, assombrando sua antiga casa. Quando uma nova família e sua filha adolescente, Lydia, mudam para a residência, o casal de fantasmas tenta, sem sucesso, assustar os novos moradores. Suas tentativas de assombração atraem um espírito espalhafatoso, cuja ajuda se torna perigosa tanto para o par de almas, quanto para a inocente Lydia.',
    year: 1988,
    imagePath: 'images/os_fantasmas_se_divertem.jpg',
    genre: 'Comédia/Fantasia',
  },
  {
    id: 19,
    title: 'Missão Impossível',
    director: 'Brian De Palma',
    storyline: 'O agente do governo Ethan Hunt e seu mentor, Jim Phelps, embarcam em uma missão secreta que toma um rumo desastroso, na qual Jim é morto e Ethan torna-se o principal suspeito do assassinato. Agora um fugitivo, Hunt recruta o brilhante Luther Stickell e o piloto Franz Krieger para ajudá-lo a entrar no prédio da CIA, fortemente vigiado, a fim de pegar um arquivo de computador confidencial que vai provar sua inocência.',
    year: 1996,
    imagePath: 'images/missao_impossivel.jpg',
    genre: 'Ação/Thriller',
  },
  {
    id: 20,
    title: 'Caravana da Coragem',
    director: 'John Korty',
    storyline: 'Uma família é separada quando os pais são sequestrados por um gigante e os filhos ficam vagando nos destroços da nave espacial deles. Os Ewoks encontram as crianças e juntos embarcam em uma jornada em busca dos pais delas.',
    year: 1984,
    imagePath: 'images/caravana_da_coragem.jpg',
    genre: 'Fantasia/Ficção Científica',
  },
  {
    id: 21,
    title: 'Harry Potter e a Pedra Filosofal',
    director: 'Chris Columbus',
    storyline: 'Harry Potter é um garoto órfão que vive infeliz com seus tios, os Dursleys. Ele recebe uma carta contendo um convite para ingressar em Hogwarts, uma famosa escola especializada em formar jovens bruxos. Inicialmente, Harry é impedido de ler a carta por seu tio, mas logo recebe a visita de Hagrid, o guarda-caça de Hogwarts, que chega para levá-lo até a escola. Harry adentra um mundo mágico que jamais imaginara, vivendo diversas aventuras com seus novos amigos, Rony Weasley e Hermione Granger.',
    year: 2001,
    imagePath: 'images/harry_potter_1.jpg',
    genre: 'Fantasia/Aventura',
  },
  {
    id: 22,
    title: 'Senhor dos Anéis e o Retorno do Rei',
    director: 'Peter Jackson',
    storyline: 'O confronto final entre as forças do bem e do mal que lutam pelo controle do futuro da Terra Média se aproxima. Sauron planeja um grande ataque a Minas Tirith, capital de Gondor, o que faz com que Gandalf e Pippin partam para o local na intenção de ajudar a resistência. Um exército é reunido por Theoden em Rohan, em mais uma tentativa de deter as forças de Sauron. Enquanto isso, Frodo, Sam e Gollum seguem sua viagem rumo à Montanha da Perdição para destruir o anel.',
    year: 2003,
    imagePath: 'images/senhor_dos_aneis.jpg',
    genre: 'Fantasia/Aventura',
  },{
    id: 23,
    title: 'Império do Sol',
    director: 'Steven Spielberg',
    storyline: 'O menino inglês Jamie Graham mora na China quando os japoneses a invadem e enviam todos os estrangeiros para campos de concentração. Jamie é capturado com um soldado americano chamado Basie, que cuida dele no campo. Embora esteja separado dos pais e em um ambiente hostil, Jamie mantém a dignidade e o otimismo, dando esperança a outros prisioneiros.',
    year: 1987,
    imagePath: 'images/império_do_sol.jpg',
    genre: 'Guerra/Drama',
  },
  {
    id: 24,
    title: 'O Poderoso Chefão - Parte II',
    director: 'Francis Ford Coppola',
    storyline: 'Após a máfia matar sua família, o jovem Vito foge da sua cidade na Sicília e vai para a América. Vito luta para manter sua família. Ele mata Black Hand Fanucci, que exigia dos comerciantes uma parte dos seus ganhos. Com a morte de Fanucci, o poderio de Vito cresce, mas sua família é o que mais importa para ele. Agora baseado no Lago Tahoe, Michael planeja fazer incursões em Las Vegas e Havana instalando negócios ligados ao lazer, mas descobre que aliados como Hyman Roth estão tentando matá-lo.',
    year: 1974,
    imagePath: 'images/o_poderoso_chefao_parte_II.jpg',
    genre: 'Crime/Drama',
  },
  {
    id: 25,
    title: 'O Iluminado',
    director: 'Stanley Kubrick',
    storyline: 'Jack Torrance se torna caseiro de inverno do isolado Hotel Overlook, nas montanhas do Colorado, na esperança de curar seu bloqueio de escritor. Ele se instala com a esposa Wendy e o filho Danny, que é atormentando por premonições. Jack não consegue escrever e as visões de Danny se tornam mais perturbadoras. O escritor descobre os segredos sombrios do hotel e começa a se transformar em um maníaco homicida, aterrorizando sua família.',
    year: 1980,
    imagePath: 'images/o_iluminado.jpeg',
    genre: 'Terror/Mistério',
  },
];

export default movies;
